import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
// import { Provider } from "@radix-ui/react-tooltip";
import { Toaster } from "@/components/ui/sonner";
import Provider from "./provider";
// import { Provider } from "@/app/provider";
const AppFont =DM_Sans({subsets: ['latin']})


export const metadata: Metadata = {
  title: "AI Video Generator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
      className={AppFont.className}>
        <Provider>
          <Toaster position="top-center" richColors/>
        {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
